# a list that contain common words used in links that are always related to site not product, ex : contact ...
common_words = ["contact", "faq", "wishlist", "wish_list", "my-account", "login", "sign", "subscribe",
                    "privacy", "policy", "customer-service", "product-support", "terms-conditions", "about-us", "setting"]
